# Generated by Django 4.2.11 on 2024-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
