# Generated by Django 4.2.11 on 2024-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_patient_is_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_login', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_login',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='idCard',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '激活')], default=0),
        ),
    ]
