# Generated by Django 4.2.11 on 2024-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_phone_number_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verification_code_created_at',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
