# Generated by Django 4.2.11 on 2024-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_doctor_verification_code_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
